### ISSUE TITLE
404 at /webpack

### ISSUE THREAD

**Issue by gregpardo** [awetzel/reaxt-example#1]
Not sure exactly what I'm supposed to be seeing at /webpack but I get the 'oops'. Is there something missing from the readme?

**Comment by awetzel** [comment]
Sorry seems to be a regression in the last reaxt version, go to `/webpack/static/index.html` until I correct this.

**Comment by awetzel** [comment]
I have just fixed the bug in `reaxt` and update `reaxt-example` to take the new version, just update it it should work now. :) . Thank you very much for trying this lib.

**Comment by gregpardo** [comment]
Yes it looks great! Thanks!
