### ISSUE TITLE
Can not find reaxt npm

### ISSUE THREAD

**Issue by swarut** [awetzel/reaxt-example#2]
I tried to run iex, then fail according to this code in lib/tasks.ex. I have no idea where to get reaxt on npm.

``` javascript
installed_version = Poison.decode!(File.read!("web/node_modules/reaxt/package.json"))["version"]
current_version = Poison.decode!(File.read!("#{:code.priv_dir(:reaxt)}/commonjs_reaxt/package.json"))["version"]
      if  installed_version !== current_version, do:
        Mix.Task.run("npm.install", args)
```

What should I do to get this pass?

**Comment by swarut** [comment]
Ah.. ok now I get it work.. seem like I did a mistake on getting the npm stuffs.

**Comment by jschoch** [comment]
how did you get this resolved?

*\* (File.Error) could not read file web/node_modules/reaxt/package.json: no such file or directory
    (elixir) lib/file.ex:245: File.read!/1
    lib/tasks.ex:44: Mix.Tasks.Compile.ReaxtWebpack.run/1
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (mix) lib/mix/tasks/compile.all.ex:15: Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.ex:64: Mix.Tasks.Compile.run/1
    (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/

**Comment by awetzel** [comment]
That means the JS part of reaxt is not installed, to do it you can add the compiler `reaxt_webpack` to your mix.exs: 

`compilers: [:reaxt_webpack] ++ Mix.compilers`

Or you can manually install it : 

`npm install /path/to/deps/reaxt/priv/commonjs_reaxt`

that's it
